apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: picsur-postgres-data
  namespace: picsur
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: truenas-iscsi-csi-retain
