apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: controller-agent-app-env
  namespace: controller-agent
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: controller-agent-vault
  target:
    name: controller-agent-app-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        OPENAI_API_KEY: "{{ .openai_api_key }}"
        SUPERVISOR_MODEL: "{{ .supervisor_model }}"
        CODE_ANALYSIS_MODEL: "{{ .code_analysis_model }}"
        JIRA_MODEL: "{{ .jira_model }}"
        JIRA_CREATE_ISSUE_MODEL: "{{ .jira_create_issue_model }}"
        JIRA_EDIT_ISSUE_MODEL: "{{ .jira_edit_issue_model }}"
        CREATE_ISSUE_DEFAULT_PROJECT: "HLAB"
        EDIT_ISSUE_ALLOWED_FIELDS: "summary,description,comment,status,assignee"
        LANGSMITH_TRACING: "false"
  data:
    - secretKey: openai_api_key
      remoteRef:
        key: k8s/controller_agent
        property: openai_api_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: supervisor_model
      remoteRef:
        key: k8s/controller_agent
        property: supervisor_model
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: code_analysis_model
      remoteRef:
        key: k8s/controller_agent
        property: code_analysis_model
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: jira_model
      remoteRef:
        key: k8s/controller_agent
        property: jira_model
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: jira_create_issue_model
      remoteRef:
        key: k8s/controller_agent
        property: jira_create_issue_model
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: jira_edit_issue_model
      remoteRef:
        key: k8s/controller_agent
        property: jira_edit_issue_model
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
