apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: controller-agent-vault
  namespace: controller-agent
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  provider:
    vault:
      server: http://192.168.1.120:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: controller-agent-vault-reader
          key: VAULT_TOKEN
