apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langflow-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: langflow-vault
  target:
    name: langflow-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: k8s/langflow
        property: db_database
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: POSTGRES_USER
      remoteRef:
        key: k8s/langflow
        property: db_username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: k8s/langflow
        property: db_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: LANGFLOW_SUPERUSER
      remoteRef:
        key: k8s/langflow
        property: superuser
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: LANGFLOW_SUPERUSER_PASSWORD
      remoteRef:
        key: k8s/langflow
        property: superuser_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: LANGFLOW_SECRET_KEY
      remoteRef:
        key: k8s/langflow
        property: secret_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
