apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: langflow-postgres-data
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: truenas-iscsi-csi-retain
