apiVersion: v1
kind: Service
metadata:
  name: langflow-postgres
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: langflow-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
