eula:
  accept: true
  company: NoDad Homelab
  email: admin@nodadyoushutup.com

clusterName: homelab

multicluster:
  enabled: false

networkPolicy:
  create: false

global:
  persistence:
    storageClass: truenas-nfs-csi-retain
    size: 20Gi
    metering:
      size: 2Gi

prometheus:
  server:
    persistentVolume:
      storageClass: truenas-nfs-csi-retain
      size: 8Gi

apiservices:
  deployed: false

resources:
  catalog-svc:
    catalog-svc:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi
