apiVersion: v1
kind: Service
metadata:
  name: seerr-postgres
  namespace: seerr
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: seerr-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
