apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: privatebin-secrets
  namespace: privatebin
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: privatebin-vault
  target:
    name: privatebin-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        POSTGRES_DB: "{{ .POSTGRES_DB }}"
        POSTGRES_USER: "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        conf.php: |
          ;<?php http_response_code(403); /*
          [main]
          discussion = true
          opendiscussion = false
          password = true
          fileupload = false
          defaultformatter = "plaintext"
          languageselection = false

          [expire]
          default = "1week"

          [expire_options]
          5min = 300
          10min = 600
          1hour = 3600
          1day = 86400
          1week = 604800
          1month = 2592000
          1year = 31536000
          never = 0

          [formatter_options]
          plaintext = "Plain Text"
          syntaxhighlighting = "Source Code"
          markdown = "Markdown"

          [traffic]
          limit = 10

          [purge]
          limit = 300
          batchsize = 10

          [model]
          class = Database
          [model_options]
          dsn = "pgsql:host=privatebin-postgres;port=5432;dbname={{ .POSTGRES_DB }}"
          tbl = "privatebin_"
          usr = "{{ .POSTGRES_USER }}"
          pwd = "{{ .POSTGRES_PASSWORD }}"
          opt[12] = true
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: k8s/privatebin
        property: db_name
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: POSTGRES_USER
      remoteRef:
        key: k8s/privatebin
        property: db_username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: k8s/privatebin
        property: db_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
