apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: privatebin-data
  namespace: privatebin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: truenas-iscsi-csi-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: privatebin-postgres-data
  namespace: privatebin
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-iscsi-csi-retain
