apiVersion: v1
kind: Namespace
metadata:
  name: qbittorrent-television-2
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/part-of: qbittorrent
    app.kubernetes.io/instance: television-2
