#!/usr/bin/env bash
# Shared, mode-aware terraform backend init + state migration for homelab pipelines.
#
# The homelab-config Terraform section is the source of truth for the state
# backend (config-id terraform/state -> .config/terraform/state.tfvars):
#
#     terraform_state = {
#       backend = "local" | "s3"
#       ...
#     }
#
# Every slice's provider.tf hardcodes `backend "s3" { key = "..." }`. That block
# is fine for S3 mode. For LOCAL mode we drop a gitignored *_override.tf next to
# it that replaces the backend with `backend "local"`, so `terraform init` runs a
# real on-disk backend with NO MinIO required. Switching modes between runs makes
# Terraform report "Backend configuration changed"; we then run
# `terraform init -migrate-state -force-copy` so the existing state is COPIED to
# the new backend (works both directions: local->s3 and s3->local), never
# abandoned.
#
# Requires the caller to have sourced resolve_config_by_id.sh and to export
# CONFIG_DIR (all homelab pipelines do). S3 mode also requires BACKEND_CONFIG to
# point at the derived minio.backend.hcl.
#
# Public functions:
#   homelab_terraform_state_mode                 -> echoes "local" or "s3"
#   homelab_terraform_init <tf_dir> [init args]  -> init (+ migrate) for that dir

# Guard against double-source.
if [[ -n "${HOMELAB_TERRAFORM_BACKEND_INIT_SOURCED:-}" ]]; then
  return 0 2>/dev/null || true
fi
HOMELAB_TERRAFORM_BACKEND_INIT_SOURCED=1

# Filename for the generated local-backend override. Ends in _override.tf so it
# is already covered by .gitignore and never committed.
HOMELAB_LOCAL_BACKEND_OVERRIDE_FILE="homelab_local_backend_override.tf"

# Resolve the desired backend mode from .config/terraform/state.tfvars. Falls
# back to "s3" (the historical default) when the file is missing/unparseable.
homelab_terraform_state_mode() {
  local config_dir="${CONFIG_DIR:-}"
  if [[ -z "${config_dir}" ]]; then
    echo "s3"
    return 0
  fi

  local state_file=""
  if declare -F homelab_resolve_config_path >/dev/null 2>&1; then
    state_file="$(homelab_resolve_config_path "${config_dir}" "terraform/state" 2>/dev/null || true)"
  fi
  if [[ -z "${state_file}" || ! -f "${state_file}" ]]; then
    echo "s3"
    return 0
  fi

  # Extract the value of `backend = "..."` from the terraform_state object.
  local mode
  mode="$(grep -oE 'backend[[:space:]]*=[[:space:]]*"[^"]*"' "${state_file}" 2>/dev/null \
    | head -n1 \
    | sed -E 's/.*"([^"]*)".*/\1/')"

  case "${mode}" in
    local) echo "local" ;;
    s3) echo "s3" ;;
    *) echo "s3" ;;
  esac
}

_homelab_write_local_override() {
  local tf_dir="$1"
  cat >"${tf_dir}/${HOMELAB_LOCAL_BACKEND_OVERRIDE_FILE}" <<'OVERRIDE'
# GENERATED by scripts/terraform/terraform_backend_init.sh - DO NOT COMMIT.
# The homelab-config Terraform state backend is set to LOCAL, so this override
# replaces the slice's `backend "s3"` with a local on-disk backend. It is
# gitignored (*_override.tf). Remove it (or switch the UI back to s3) to use
# the MinIO S3 backend again; the pipeline manages this file automatically.
terraform {
  backend "local" {
    path = "terraform.tfstate"
  }
}
OVERRIDE
}

_homelab_remove_local_override() {
  local tf_dir="$1"
  rm -f "${tf_dir}/${HOMELAB_LOCAL_BACKEND_OVERRIDE_FILE}"
}

# Best-effort snapshot of the currently-initialized state before a migration, so
# an operator can recover if a migration goes wrong. Gitignored (*.tfstate.*).
_homelab_backup_state() {
  local tf_dir="$1"
  local stamp backup
  stamp="$(date +%Y%m%d%H%M%S)"
  backup="terraform.tfstate.backup-${stamp}"
  if (cd "${tf_dir}" && terraform state pull >"${backup}" 2>/dev/null); then
    # Drop empty/failed pulls so we don't leave noise behind.
    if [[ ! -s "${tf_dir}/${backup}" ]]; then
      rm -f "${tf_dir}/${backup}"
    else
      echo "[INFO] Backed up current state to ${tf_dir}/${backup} before migration"
    fi
  else
    rm -f "${tf_dir}/${backup}" 2>/dev/null || true
  fi
}

# Mode-aware `terraform init` for a slice directory, with automatic state
# migration when the backend changed. Extra args after <tf_dir> are forwarded to
# every terraform init invocation.
homelab_terraform_init() {
  local tf_dir="$1"
  shift || true

  if [[ -z "${tf_dir}" || ! -d "${tf_dir}" ]]; then
    echo "[ERR] homelab_terraform_init: invalid terraform dir: ${tf_dir}" >&2
    return 1
  fi

  local mode
  mode="$(homelab_terraform_state_mode)"

  local -a init_args=()
  if [[ "${mode}" == "local" ]]; then
    echo "[INFO] Terraform state backend: LOCAL (self-init, no MinIO required)"
    _homelab_write_local_override "${tf_dir}"
  else
    echo "[INFO] Terraform state backend: S3 (MinIO)"
    _homelab_remove_local_override "${tf_dir}"
    if [[ -z "${BACKEND_CONFIG:-}" || ! -f "${BACKEND_CONFIG}" ]]; then
      echo "[ERR] S3 backend selected but backend config is missing: ${BACKEND_CONFIG:-<unset>}" >&2
      echo "      Set the Terraform state backend to local in homelab-config, or configure MinIO." >&2
      return 1
    fi
    init_args=(-backend-config="${BACKEND_CONFIG}")
  fi

  local init_log
  init_log="$(mktemp -t homelab-terraform-init-XXXXXX)"

  if (
    cd "${tf_dir}"
    terraform init "${init_args[@]}" "$@"
  ) > >(tee "${init_log}") 2> >(tee -a "${init_log}" >&2); then
    rm -f "${init_log}"
    return 0
  fi

  if grep -q "Backend configuration changed" "${init_log}"; then
    echo "[WARN] Backend change detected for ${tf_dir}; migrating existing state (${mode})"
    _homelab_backup_state "${tf_dir}"
    if (
      cd "${tf_dir}"
      terraform init -migrate-state -force-copy "${init_args[@]}" "$@"
    ); then
      rm -f "${init_log}"
      return 0
    fi
    # -migrate-state failed. -reconfigure does NOT move state, so it is a last
    # resort for a stale cached record (e.g. a copied checkout) - warn loudly.
    echo "[WARN] State migration failed for ${tf_dir}; falling back to terraform init -reconfigure" >&2
    echo "       (this does NOT migrate state - verify the result before applying)" >&2
    if (
      cd "${tf_dir}"
      terraform init -reconfigure "${init_args[@]}" "$@"
    ); then
      rm -f "${init_log}"
      return 0
    fi
  fi

  rm -f "${init_log}"
  return 1
}
