apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-fortigate-app-env
  namespace: mcp-fortigate
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: mcp-fortigate-vault
  target:
    name: mcp-fortigate-app-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        FORTIGATE_API_TOKEN: '{{ .fortigate_api_token | default "" }}'
        FORTIGATE_USERNAME: '{{ .fortigate_username | default "" }}'
        FORTIGATE_PASSWORD: '{{ .fortigate_password | default "" }}'
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: k8s/mcp_fortigate
        metadataPolicy: None
