apiVersion: v1
kind: Namespace
metadata:
  name: qbittorrent-freeleech
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/part-of: qbittorrent
    app.kubernetes.io/instance: freeleech
