apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-github-app-env
  namespace: mcp-github
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: mcp-github-vault
  target:
    name: mcp-github-app-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        GITHUB_PERSONAL_ACCESS_TOKEN: "{{ .github_personal_access_token }}"
  data:
    - secretKey: github_personal_access_token
      remoteRef:
        key: k8s/mcp_github
        property: github_personal_access_token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
