apiVersion: v1
kind: Service
metadata:
  name: mcp-github
  namespace: mcp-github
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  selector:
    app.kubernetes.io/name: mcp-github
  ports:
    - name: http
      port: 8082
      targetPort: http
