apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-cloudflare-app-env
  namespace: mcp-cloudflare
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: mcp-cloudflare-vault
  target:
    name: mcp-cloudflare-app-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        CLOUDFLARE_API_TOKEN: "{{ .cloudflare_api_token }}"
        CLOUDFLARE_ZONE_ID: "{{ .cloudflare_zone_id }}"
        CLOUDFLARE_EMAIL: '{{ .cloudflare_email | default "" }}'
  data:
    - secretKey: cloudflare_api_token
      remoteRef:
        key: k8s/mcp_cloudflare
        property: cloudflare_api_token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: cloudflare_zone_id
      remoteRef:
        key: k8s/mcp_cloudflare
        property: cloudflare_zone_id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: cloudflare_email
      remoteRef:
        key: k8s/mcp_cloudflare
        property: cloudflare_email
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
