apiVersion: v1
kind: Service
metadata:
  name: mcp-cloudflare
  namespace: mcp-cloudflare
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  selector:
    app.kubernetes.io/name: mcp-cloudflare
  ports:
    - name: http
      port: 8084
      targetPort: http
