apiVersion: v1
kind: Service
metadata:
  name: langgraph
  namespace: langgraph
spec:
  selector:
    app.kubernetes.io/name: langgraph
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
