apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-google-workspace-app-env
  namespace: mcp-google-workspace
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: mcp-google-workspace-vault
  target:
    name: mcp-google-workspace-app-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        WORKSPACE_MCP_DELEGATED_USER: "{{ .workspace_delegated_user }}"
        GOOGLE_WORKSPACE_MCP_TOOL_TIER: "{{ .workspace_tool_tier }}"
        GOOGLE_WORKSPACE_MCP_READ_ONLY: "{{ .workspace_read_only }}"
  data:
    - secretKey: workspace_delegated_user
      remoteRef:
        key: k8s/mcp_google_workspace
        property: workspace_delegated_user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: workspace_tool_tier
      remoteRef:
        key: k8s/mcp_google_workspace
        property: workspace_tool_tier
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: workspace_read_only
      remoteRef:
        key: k8s/mcp_google_workspace
        property: workspace_read_only
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
