apiVersion: v1
kind: Service
metadata:
  name: mcp-google-workspace
  namespace: mcp-google-workspace
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  selector:
    app.kubernetes.io/name: mcp-google-workspace
  ports:
    - name: http
      port: 8086
      targetPort: http
