apiVersion: v1
kind: Secret
metadata:
  name: cross-seed-secrets
  namespace: cross-seed-bhd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
type: Opaque
stringData:
  CROSS_SEED_API_KEY: REPLACE_WITH_24_CHAR_OR_LONGER_API_KEY
  CROSS_SEED_TORZNAB_BHD_URL: ""
  CROSS_SEED_SONARR_URL: ""
  CROSS_SEED_RADARR_URL: ""
  CROSS_SEED_QBIT_USERNAME: admin
  CROSS_SEED_QBIT_READONLY_PASSWORD: S#nvhs89vher
  CROSS_SEED_QBIT_BHD_PASSWORD: S#nvhs89vher
