apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-3fbda2f1-7dd1-4806-9c05-f9424dbe29c0
  labels:
    app.kubernetes.io/instance: clusterplex
    app.kubernetes.io/name: transcode
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 100Gi
  csi:
    driver: org.democratic-csi.truenas-nfs
    fsType: nfs
    volumeHandle: pvc-3fbda2f1-7dd1-4806-9c05-f9424dbe29c0
    volumeAttributes:
      node_attach_driver: nfs
      provisioner_driver: freenas-api-nfs
      provisioner_driver_instance_id: homelab-nfs
      server: 192.168.1.100
      share: /mnt/eapp/k8s/nfs/vols/pvc-3fbda2f1-7dd1-4806-9c05-f9424dbe29c0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-nfs-csi-retain
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: clusterplex-transcode
    namespace: clusterplex
  volumeMode: Filesystem
