apiVersion: v1
kind: PersistentVolume
metadata:
  name: clusterplex-media
  labels:
    app.kubernetes.io/name: clusterplex-media
    app.kubernetes.io/part-of: clusterplex
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  storageClassName: clusterplex-media-static
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
  nfs:
    server: 192.168.1.100
    path: /mnt/epool/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterplex-media
  namespace: clusterplex
  labels:
    app.kubernetes.io/name: clusterplex-media
    app.kubernetes.io/part-of: clusterplex
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: clusterplex-media-static
  volumeName: clusterplex-media
