apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: prowlarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-iscsi-csi-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-postgres-data
  namespace: prowlarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: truenas-iscsi-csi-retain
