apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
data:
  admin.enabled: "true"
  accounts.admin: apiKey, login
  exec.enabled: "true"
