apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: clusterplex
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  description: ClusterPlex manifests managed from homelab GitOps repo
  sourceRepos:
    - https://pabloromeo.github.io/clusterplex
    - git@github.com:nodadyoushutup/homelab.git
    - https://github.com/nodadyoushutup/homelab.git
  destinations:
    - namespace: clusterplex
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusterplex
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "31"
spec:
  project: clusterplex
  destination:
    server: https://kubernetes.default.svc
    namespace: clusterplex
  source:
    repoURL: git@github.com:nodadyoushutup/homelab.git
    targetRevision: HEAD
    path: kubernetes/clusterplex
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      name: clusterplex-worker
      jsonPointers:
        - /spec/volumeClaimTemplates
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
