apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusterplex
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "31"
spec:
  project: clusterplex
  destination:
    server: https://kubernetes.default.svc
    namespace: clusterplex
  source:
    repoURL: git@github.com:nodadyoushutup/homelab.git
    targetRevision: HEAD
    path: kubernetes/clusterplex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
