apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: democratic-csi-nfs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  description: democratic-csi NFS platform addon
  sourceRepos:
    - git@github.com:nodadyoushutup/homelab.git
    - https://github.com/nodadyoushutup/homelab.git
    - https://democratic-csi.github.io/charts
  destinations:
    - namespace: democratic-csi-nfs
      server: https://kubernetes.default.svc
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi-nfs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "26"
spec:
  project: democratic-csi-nfs
  revisionHistoryLimit: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: democratic-csi-nfs
  sources:
    - repoURL: https://democratic-csi.github.io/charts
      chart: democratic-csi
      targetRevision: "0.15.1"
      helm:
        releaseName: democratic-csi-nfs
        valueFiles:
          - $values/kubernetes/democratic-csi-nfs/values.yaml
    - repoURL: git@github.com:nodadyoushutup/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: git@github.com:nodadyoushutup/homelab.git
      targetRevision: HEAD
      path: kubernetes/democratic-csi-nfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
