apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k10
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "34"
spec:
  project: default
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: catalog-svc
      namespace: kasten-io
      jqPathExpressions:
        - .spec.template.spec.containers[] | select(.name=="catalog-svc") | .livenessProbe
        - .spec.template.spec.containers[] | select(.name=="catalog-svc") | .readinessProbe
  destination:
    server: https://kubernetes.default.svc
    namespace: kasten-io
  source:
    repoURL: https://charts.kasten.io/
    chart: k10
    targetRevision: 8.5.4
    helm:
      releaseName: k10
      values: |
        eula:
          accept: true
          company: NoDad Homelab
          email: admin@nodadyoushutup.com

        clusterName: homelab

        multicluster:
          enabled: false

        networkPolicy:
          create: false

        global:
          persistence:
            storageClass: truenas-nfs-csi-retain
            size: 20Gi
            metering:
              size: 2Gi

        prometheus:
          server:
            persistentVolume:
              storageClass: truenas-nfs-csi-retain
              size: 8Gi

        apiservices:
          deployed: false

        resources:
          catalog-svc:
            catalog-svc:
              requests:
                cpu: 500m
                memory: 1Gi
              limits:
                cpu: 2000m
                memory: 2Gi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
