apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: langgraph
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "48"
spec:
  project: langgraph
  destination:
    server: https://kubernetes.default.svc
    namespace: langgraph
  source:
    repoURL: git@github.com:nodadyoushutup/homelab.git
    targetRevision: HEAD
    path: kubernetes/langgraph
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
