apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: privatebin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "44"
spec:
  project: privatebin
  destination:
    server: https://kubernetes.default.svc
    namespace: privatebin
  source:
    repoURL: git@github.com:nodadyoushutup/homelab.git
    targetRevision: HEAD
    path: kubernetes/privatebin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
