apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent-movie-7
  namespace: argocd
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/part-of: qbittorrent
    app.kubernetes.io/instance: movie-7
  annotations:
    argocd.argoproj.io/sync-wave: "57"
spec:
  project: qbittorrent
  destination:
    server: https://kubernetes.default.svc
    namespace: qbittorrent-movie-7
  source:
    repoURL: git@github.com:nodadyoushutup/homelab.git
    targetRevision: HEAD
    path: kubernetes/qbittorrent/overlays/movie-7
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
