apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent-torrents
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: qbittorrent
  destination:
    server: https://kubernetes.default.svc
    namespace: qbittorrent-torrents
  source:
    repoURL: git@github.com:nodadyoushutup/homelab.git
    targetRevision: HEAD
    path: kubernetes/qbittorrent/overlays/torrents
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
