apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qbittorrent-books
  namespace: argocd
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/part-of: qbittorrent
    app.kubernetes.io/instance: books
  annotations:
    argocd.argoproj.io/sync-wave: "90"
spec:
  project: qbittorrent
  destination:
    server: https://kubernetes.default.svc
    namespace: qbittorrent-books
  source:
    repoURL: git@github.com:nodadyoushutup/homelab.git
    targetRevision: HEAD
    path: kubernetes/qbittorrent/overlays/books
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
