apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: qbittorrent
  namespace: argocd
  labels:
    app.kubernetes.io/name: qbittorrent
    app.kubernetes.io/part-of: qbittorrent
  annotations:
    argocd.argoproj.io/sync-wave: "38"
spec:
  description: qBittorrent instances managed from homelab GitOps repo
  sourceRepos:
    - git@github.com:nodadyoushutup/homelab.git
    - https://github.com/nodadyoushutup/homelab.git
  destinations:
    - namespace: qbittorrent-movie-0
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-movie-1
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-movie-2
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-movie-3
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-movie-4
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-movie-5
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-movie-6
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-movie-7
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-movie-8
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-movie-9
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-movie-10
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-television-0
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-television-1
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-television-2
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-cross-seed-ab
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-cross-seed-ant
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-cross-seed-ath
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-cross-seed-bhd
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-cross-seed-blu
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-cross-seed-cg
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-cross-seed-hdb
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-cross-seed-kg
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-cross-seed-sc
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-upload
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-books
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-xxx
      server: https://kubernetes.default.svc
    - namespace: qbittorrent-freeleech
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
