apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  project: radarr
  destination:
    server: https://kubernetes.default.svc
    namespace: radarr
  source:
    repoURL: git@github.com:nodadyoushutup/homelab.git
    targetRevision: HEAD
    path: kubernetes/radarr
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
