apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "29"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: snapshot-controller
  source:
    repoURL: https://piraeus.io/helm-charts
    chart: snapshot-controller
    targetRevision: 4.1.0
    helm:
      releaseName: snapshot-controller
      values: |
        controller:
          image:
            tag: v8.2.1

          volumeSnapshotClasses:
            - name: truenas-iscsi-snapclass
              annotations:
                k10.kasten.io/is-snapshot-class: "true"
                snapshot.storage.kubernetes.io/is-default-class: "true"
              labels:
                velero.io/csi-volumesnapshot-class: "true"
              driver: org.democratic-csi.truenas-iscsi
              deletionPolicy: Delete
            - name: truenas-nfs-snapclass
              annotations:
                k10.kasten.io/is-snapshot-class: "true"
                snapshot.storage.kubernetes.io/is-default-class: "true"
              labels:
                velero.io/csi-volumesnapshot-class: "true"
              driver: org.democratic-csi.truenas-nfs
              deletionPolicy: Delete
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
