apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tautulli
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "31"
spec:
  project: tautulli
  destination:
    server: https://kubernetes.default.svc
    namespace: tautulli
  source:
    repoURL: git@github.com:nodadyoushutup/homelab.git
    targetRevision: HEAD
    path: kubernetes/tautulli
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
