apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tautulli
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  description: Tautulli manifests managed from homelab GitOps repo
  sourceRepos:
    - git@github.com:nodadyoushutup/homelab.git
    - https://github.com/nodadyoushutup/homelab.git
  destinations:
    - namespace: tautulli
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
