apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-secrets
  namespace: radarr
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: radarr-vault
  target:
    name: radarr-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: k8s/radarr
        property: db_main_db
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: POSTGRES_LOG_DB
      remoteRef:
        key: k8s/radarr
        property: db_log_db
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: POSTGRES_USER
      remoteRef:
        key: k8s/radarr
        property: db_username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: k8s/radarr
        property: db_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
