apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: radarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: truenas-iscsi-csi-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-v2
  namespace: radarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: truenas-iscsi-csi-retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-postgres-data
  namespace: radarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: truenas-iscsi-csi-retain
