apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: thelounge-bootstrap
  namespace: thelounge
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: thelounge-vault
  target:
    name: thelounge-bootstrap
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
  data:
    - secretKey: TL_USERNAME
      remoteRef:
        key: k8s/thelounge
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: TL_PASSWORD
      remoteRef:
        key: k8s/thelounge
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: profile
      remoteRef:
        key: k8s/thelounge
        property: profile
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
