apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thelounge-data
  namespace: thelounge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: truenas-iscsi-csi-retain
