apiVersion: v1
kind: Service
metadata:
  name: mcp-filesystem
  namespace: mcp-filesystem
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  selector:
    app.kubernetes.io/name: mcp-filesystem
  ports:
    - name: http
      port: 8098
      targetPort: http
