apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-atlassian-app-env
  namespace: mcp-atlassian
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: mcp-atlassian-vault
  target:
    name: mcp-atlassian-app-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        JIRA_URL: "{{ .jira_url }}"
        JIRA_USERNAME: "{{ .jira_username }}"
        JIRA_API_TOKEN: "{{ .jira_api_token }}"
        CONFLUENCE_URL: "{{ .confluence_url }}"
        CONFLUENCE_USERNAME: "{{ .confluence_username }}"
        CONFLUENCE_API_TOKEN: "{{ .confluence_api_token }}"
        JIRA_PROJECTS_FILTER: "{{ .jira_projects_filter }}"
        CONFLUENCE_SPACES_FILTER: "{{ .confluence_spaces_filter }}"
  data:
    - secretKey: jira_url
      remoteRef:
        key: k8s/mcp_atlassian
        property: jira_url
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: jira_username
      remoteRef:
        key: k8s/mcp_atlassian
        property: jira_username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: jira_api_token
      remoteRef:
        key: k8s/mcp_atlassian
        property: jira_api_token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: confluence_url
      remoteRef:
        key: k8s/mcp_atlassian
        property: confluence_url
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: confluence_username
      remoteRef:
        key: k8s/mcp_atlassian
        property: confluence_username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: confluence_api_token
      remoteRef:
        key: k8s/mcp_atlassian
        property: confluence_api_token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: jira_projects_filter
      remoteRef:
        key: k8s/mcp_atlassian
        property: jira_projects_filter
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: confluence_spaces_filter
      remoteRef:
        key: k8s/mcp_atlassian
        property: confluence_spaces_filter
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
