apiVersion: v1
kind: Service
metadata:
  name: mcp-atlassian
  namespace: mcp-atlassian
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  selector:
    app.kubernetes.io/name: mcp-atlassian
  ports:
    - name: http
      port: 8000
      targetPort: http
