apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - overlays/movie-0
  - overlays/movie-1
  - overlays/movie-2
  - overlays/movie-3
  - overlays/movie-4
  - overlays/movie-5
  - overlays/movie-6
  - overlays/movie-7
  - overlays/movie-8
  - overlays/movie-9
  - overlays/movie-10
  - overlays/movie-4k
  - overlays/television-0
  - overlays/television-1
  - overlays/television-2
  - overlays/cross-seed-ab
  - overlays/cross-seed-ant
  - overlays/cross-seed-ath
  - overlays/cross-seed-bhd
  - overlays/cross-seed-blu
  - overlays/cross-seed-cg
  - overlays/cross-seed-hdb
  - overlays/cross-seed-kg
  - overlays/cross-seed-sc
  - overlays/upload
  - overlays/books
  - overlays/xxx
  - overlays/freeleech
