"""Docker provider catalog helpers and
``.config/terraform/providers/docker.tfvars`` read/write.

The file is generated by homelab-config and consumed by every Swarm Terraform
slice as a shared ``-var-file``. It holds two things:

- ``docker_providers``: a map keyed by machine name. Entries are **derived** from
  machine definitions: swarm nodes (``.config/docker/swarm.tfvars``) plus non-swarm
  extra hosts (``.config/docker/extra_hosts.yaml``). Each entry is
  ``{host, ssh_opts}`` for the ``kreuzwerker/docker`` provider.
- ``registry_auths``: a shared, editable list of ``{address, username, password}``
  used by every slice's ``registry_auth`` blocks. This is the only editable state
  stored in this file; the providers map is re-derived on every render.

The file holds secrets and lives under ``.config`` (git-ignored) - never commit it.
"""

from __future__ import annotations

import logging
from collections.abc import Iterable
from pathlib import Path

import hcl2

from homelab_config.hcl_util import atomic_write, coerce_str, hcl_escape
from homelab_config.paths import DOCKER_TFVARS, SSH_DIR
from homelab_config.swarm_config import DEFAULT_SSH_PORT

logger = logging.getLogger(__name__)

_CONFIG_TAG = "# homelab-config: terraform/providers/docker"
_HEADER = (
    f"{_CONFIG_TAG}\n"
    "# Docker provider catalog, managed by the homelab-config web app\n"
    "# (applications/homelab_config).\n"
    "# Generated file: providers are derived from docker/swarm.tfvars (swarm nodes)\n"
    "# and docker/extra_hosts.yaml (non-swarm hosts); edit registry_auths in the UI.\n"
    "#\n"
    "# Consumed by every Swarm Terraform slice as a shared -var-file: a slice\n"
    "# selects a machine by name (docker_machine) and reuses registry_auths.\n"
    "# This file holds secrets and lives under .config (git-ignored) - never commit it.\n"
)


class DockerConfigError(ValueError):
    """Raised when a registry auth payload fails validation."""


# -- ssh / provider derivation ------------------------------------------------


def ssh_dir_abs() -> str:
    """Absolute path to the managed ``.config/.ssh`` directory (for ssh_opts)."""
    return str(SSH_DIR)


def build_ssh_opts(ssh_key: str, ssh_dir: str) -> list[str]:
    """Build the docker provider ``ssh_opts`` list for a key set under ssh_dir."""
    opts = [
        "-o",
        "StrictHostKeyChecking=no",
        "-o",
        f"UserKnownHostsFile={ssh_dir}/known_hosts",
    ]
    if ssh_key:
        opts += ["-i", f"{ssh_dir}/{ssh_key}/id_ed25519"]
    return opts


def _machine_host(machine: dict) -> str:
    """``ssh://<user>@<host>`` (append ``:<port>`` only when port != 22)."""
    user = machine.get("ssh_user") or ""
    host = machine.get("host") or ""
    port = machine.get("ssh_port", DEFAULT_SSH_PORT)
    base = f"ssh://{user}@{host}" if user else f"ssh://{host}"
    if port and int(port) != DEFAULT_SSH_PORT:
        base = f"{base}:{port}"
    return base


def provider_from_machine(machine: dict, ssh_dir: str) -> dict:
    """Build a ``{host, ssh_opts}`` provider entry from a machine dict.

    Works for both swarm nodes and extra hosts (same host/ssh_user/ssh_port/
    ssh_key shape).
    """
    return {
        "host": _machine_host(machine),
        "ssh_opts": build_ssh_opts(machine.get("ssh_key") or "", ssh_dir),
    }


# -- registry validation ------------------------------------------------------


def normalize_registry_auth(data: dict) -> dict:
    """Validate/normalize a registry auth entry (address/username/password)."""
    address = str(data.get("address") or "").strip()
    if not address:
        raise DockerConfigError("address is required")
    username = str(data.get("username") or "").strip()
    password = "" if data.get("password") is None else str(data.get("password"))
    return {"address": address, "username": username, "password": password}


def order_registry_auths(auths: Iterable[dict]) -> list[dict]:
    return sorted(auths, key=lambda a: a.get("address", ""))


def canonical_registry_auths(auths: Iterable[dict]) -> tuple:
    """Order-insensitive, hashable form of the registry auths (for drift)."""
    return tuple(
        (a.get("address", ""), a.get("username", ""), a.get("password", ""))
        for a in order_registry_auths(auths)
    )


# -- render --------------------------------------------------------------------


def _render_provider_block(name: str, entry: dict) -> str:
    opts = "".join(f'      "{hcl_escape(opt)}",\n' for opt in entry["ssh_opts"])
    return (
        f'  "{hcl_escape(name)}" = {{\n'
        f'    host = "{hcl_escape(entry["host"])}"\n'
        f"    ssh_opts = [\n"
        f"{opts}"
        f"    ]\n"
        f"  }}\n"
    )


def _render_registry_block(auth: dict) -> str:
    return (
        "  {\n"
        f'    address  = "{hcl_escape(auth["address"])}"\n'
        f'    username = "{hcl_escape(auth["username"])}"\n'
        f'    password = "{hcl_escape(auth["password"])}"\n'
        "  },\n"
    )


def render_docker_tfvars(
    nodes: Iterable[dict],
    extra_hosts: Iterable[dict],
    registry_auths: Iterable[dict],
    ssh_dir: str | None = None,
) -> str:
    """Render docker.tfvars: derived swarm + extra-host providers + registry_auths.

    ``nodes`` and ``extra_hosts`` are machine dicts (name/host/ssh_user/ssh_port/
    ssh_key); both are rendered into ``docker_providers`` (swarm nodes first, then
    extra hosts sorted by name).
    """
    ssh_dir = ssh_dir or ssh_dir_abs()

    body = "docker_providers = {\n"
    for node in nodes:
        body += _render_provider_block(node["name"], provider_from_machine(node, ssh_dir))
    for host in sorted(extra_hosts, key=lambda h: h.get("name", "")):
        body += _render_provider_block(host["name"], provider_from_machine(host, ssh_dir))
    body += "}\n\n"

    body += "registry_auths = [\n"
    body += "".join(_render_registry_block(a) for a in order_registry_auths(registry_auths))
    body += "]\n"

    return f"{_HEADER}{body}"


# -- read ----------------------------------------------------------------------


def read_registry_auths(path: Path = DOCKER_TFVARS) -> list[dict] | None:
    """Parse docker.tfvars and return its ``registry_auths`` list.

    Returns ``None`` when the file is missing or unparsable. The ``docker_providers``
    map is derived elsewhere, so it is ignored here.
    """
    if not path.is_file():
        return None
    try:
        with path.open("r", encoding="utf-8") as handle:
            data = hcl2.load(handle)
    except Exception as exc:  # noqa: BLE001 - hcl2 raises assorted errors
        logger.warning("Could not parse Docker catalog %s: %s", path, exc)
        return None
    if not isinstance(data, dict):
        return None

    registry_auths: list[dict] = []
    raw_auths = data.get("registry_auths")
    if isinstance(raw_auths, list):
        for entry in raw_auths:
            if not isinstance(entry, dict):
                continue
            try:
                registry_auths.append(
                    normalize_registry_auth(
                        {
                            "address": coerce_str(entry.get("address")),
                            "username": coerce_str(entry.get("username")),
                            "password": coerce_str(entry.get("password")),
                        }
                    )
                )
            except DockerConfigError as exc:
                logger.warning("Skipping invalid registry auth in %s: %s", path, exc)
    return registry_auths


def write_docker_tfvars(
    nodes: Iterable[dict],
    extra_hosts: Iterable[dict],
    registry_auths: Iterable[dict],
    path: Path = DOCKER_TFVARS,
) -> Path:
    """Write docker.tfvars atomically and return it."""
    content = render_docker_tfvars(nodes, extra_hosts, registry_auths)
    atomic_write(path, content)
    logger.info("Wrote Docker catalog to %s", path)
    return path


__all__ = [
    "DockerConfigError",
    "build_ssh_opts",
    "canonical_registry_auths",
    "normalize_registry_auth",
    "order_registry_auths",
    "provider_from_machine",
    "read_registry_auths",
    "render_docker_tfvars",
    "ssh_dir_abs",
    "write_docker_tfvars",
]
