apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cross-seed
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "36"
spec:
  description: cross-seed manifests managed from homelab GitOps repo
  sourceRepos:
    - git@github.com:nodadyoushutup/homelab.git
    - https://github.com/nodadyoushutup/homelab.git
  destinations:
    - namespace: cross-seed-bhd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cross-seed-bhd
  namespace: argocd
  labels:
    app.kubernetes.io/name: cross-seed
    app.kubernetes.io/part-of: cross-seed
    app.kubernetes.io/instance: bhd
  annotations:
    argocd.argoproj.io/sync-wave: "83"
spec:
  project: cross-seed
  destination:
    server: https://kubernetes.default.svc
    namespace: cross-seed-bhd
  source:
    repoURL: git@github.com:nodadyoushutup/homelab.git
    targetRevision: HEAD
    path: kubernetes/cross-seed/overlays/bhd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
