apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k10-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  project: default
  ignoreDifferences:
    - group: config.kio.kasten.io
      kind: Policy
      jqPathExpressions:
        - .spec.actions[]?.exportParameters?.migrationToken
        - .spec.actions[]?.exportParameters?.receiveString
  destination:
    server: https://kubernetes.default.svc
    namespace: kasten-io
  source:
    repoURL: git@github.com:nodadyoushutup/homelab.git
    targetRevision: HEAD
    path: kubernetes/k10-config
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
