apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k10
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "34"
spec:
  project: default
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: catalog-svc
      namespace: kasten-io
      jqPathExpressions:
        - .spec.template.spec.containers[] | select(.name=="catalog-svc") | .livenessProbe
        - .spec.template.spec.containers[] | select(.name=="catalog-svc") | .readinessProbe
    - group: config.kio.kasten.io
      kind: Policy
      jqPathExpressions:
        - .spec.actions[]?.exportParameters?.migrationToken
        - .spec.actions[]?.exportParameters?.receiveString
  destination:
    server: https://kubernetes.default.svc
    namespace: kasten-io
  sources:
    - repoURL: https://charts.kasten.io/
      chart: k10
      targetRevision: 8.5.4
      helm:
        releaseName: k10
        valueFiles:
          - $values/kubernetes/k10/values.yaml
    - repoURL: git@github.com:nodadyoushutup/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: git@github.com:nodadyoushutup/homelab.git
      targetRevision: HEAD
      path: kubernetes/k10/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
