apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterplex.yaml
  - cross-seed.yaml
  - democratic-csi-iscsi.yaml
  - democratic-csi-nfs.yaml
  - external-secrets.yaml
  - ingress-nginx.yaml
  - langchain-agent-chat.yaml
  - langgraph.yaml
  - metallb.yaml
  - node-exporter-k8s.yaml
  - picsur.yaml
  - privatebin.yaml
  - prowlarr.yaml
  - qbittorrent.yaml
  - radarr.yaml
  - seerr.yaml
  - snapshot-controller.yaml
  - sonarr.yaml
  - tautulli.yaml
  - thelounge.yaml
  - velero.yaml
