apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: radarr-4k
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "39"
spec:
  description: Radarr 4K manifests managed from homelab GitOps repo
  sourceRepos:
    - git@github.com:nodadyoushutup/homelab.git
    - https://github.com/nodadyoushutup/homelab.git
  destinations:
    - namespace: radarr-4k
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr-4k
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: radarr-4k
  destination:
    server: https://kubernetes.default.svc
    namespace: radarr-4k
  source:
    repoURL: git@github.com:nodadyoushutup/homelab.git
    targetRevision: HEAD
    path: kubernetes/radarr-4k
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
