apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "31"
spec:
  description: Velero backup platform addon
  sourceRepos:
    - git@github.com:nodadyoushutup/homelab.git
    - https://github.com/nodadyoushutup/homelab.git
    - https://vmware-tanzu.github.io/helm-charts
  destinations:
    - namespace: velero
      server: https://kubernetes.default.svc
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "32"
    argocd.argoproj.io/sync-options: SkipHooks=true
spec:
  project: velero
  revisionHistoryLimit: 0
  ignoreDifferences:
    - group: apps
      kind: Deployment
      namespace: velero
      name: velero
      jqPathExpressions:
        - .spec.template.metadata.annotations
    - group: ""
      kind: Secret
      namespace: velero
      name: velero-s3-credentials
      jqPathExpressions:
        - .data
    - group: external-secrets.io
      kind: ExternalSecret
      namespace: velero
      name: velero-s3-credentials
      jqPathExpressions:
        - .metadata.labels
        - .metadata.annotations
        - .status
    - group: batch
      kind: Job
      namespace: velero
      jqPathExpressions:
        - .status
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: "12.0.1"
      helm:
        releaseName: velero
        valueFiles:
          - $values/kubernetes/velero/values.yaml
    - repoURL: git@github.com:nodadyoushutup/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: git@github.com:nodadyoushutup/homelab.git
      targetRevision: HEAD
      path: kubernetes/velero/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
      - SkipHooks=true
