apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "31"
spec:
  description: Velero backup platform addon
  sourceRepos:
    - git@github.com:nodadyoushutup/homelab.git
    - https://github.com/nodadyoushutup/homelab.git
    - https://vmware-tanzu.github.io/helm-charts
  destinations:
    - namespace: velero
      server: https://kubernetes.default.svc
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "32"
spec:
  project: velero
  revisionHistoryLimit: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  sources:
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: "12.0.1"
      helm:
        releaseName: velero
        valueFiles:
          - $values/kubernetes/velero/values.yaml
    - repoURL: git@github.com:nodadyoushutup/homelab.git
      targetRevision: HEAD
      ref: values
    - repoURL: git@github.com:nodadyoushutup/homelab.git
      targetRevision: HEAD
      path: kubernetes/velero/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
