apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: qbittorrent-vault
  namespace: qbittorrent-movie-0
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  provider:
    vault:
      server: http://192.168.1.20:8200
      path: secret
      version: v2
      auth:
        tokenSecretRef:
          name: qbittorrent-vault-reader
          key: VAULT_TOKEN
