version: 1
config:
  - type: physical
    name: eth0
    mac_address: "BC:24:11:F3:49:7C"
    subnets:
      - type: static
        address: 192.168.1.212
        netmask: 255.255.255.0
        gateway: 192.168.1.1
