{
 "title": "Docker",
 "tags": [
  "homelab",
  "docker",
  "telegraf"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "platform",
    "label": "Type",
    "query": "label_values(up{job=\"telegraf_docker_metrics\"}, platform)"
   },
   {
    "name": "node",
    "label": "Host",
    "query": "label_values(docker_n_containers_running{job=\"telegraf_docker_metrics\", platform=~\"$platform\"}, engine_host)"
   }
  ]
 },
 "panels": [
  { "title": "Hosts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (engine_host) (docker_n_containers_running{job=\"telegraf_docker_metrics\", platform=~\"$platform\"}))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Online hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (engine_host) (up{job=\"telegraf_docker_metrics\", platform=~\"$platform\"} * on(instance) group_left(engine_host) count by(instance, engine_host)(docker_n_containers_running{job=\"telegraf_docker_metrics\", platform=~\"$platform\"})) == 1)",
     "legendFormat": "online"
    }
   ]
  },
  {
   "title": "Offline hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (engine_host) (up{job=\"telegraf_docker_metrics\", platform=~\"$platform\"} * on(instance) group_left(engine_host) count by(instance, engine_host)(docker_n_containers_running{job=\"telegraf_docker_metrics\", platform=~\"$platform\"})) == 0)",
     "legendFormat": "offline"
    }
   ]
  },
  {
   "title": "Online",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max by (engine_host, platform) (up{job=\"telegraf_docker_metrics\", platform=~\"$platform\"} * on(instance) group_left(engine_host) count by(instance, engine_host)(docker_n_containers_running{job=\"telegraf_docker_metrics\", platform=~\"$platform\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "max by (engine_host, platform) (up{job=\"telegraf_docker_metrics\", platform=~\"$platform\"} * on(instance) group_left(engine_host) count by(instance, engine_host)(docker_n_containers_running{job=\"telegraf_docker_metrics\", platform=~\"$platform\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Averages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(docker_container_cpu_usage_percent{job=\"telegraf_docker_metrics\", platform=~\"$platform\", engine_host=~\"$node\", com_docker_swarm_service_name!=\"\", container_status=\"running\"})",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(docker_container_mem_usage_percent{job=\"telegraf_docker_metrics\", platform=~\"$platform\", engine_host=~\"$node\", com_docker_swarm_service_name!=\"\", container_status=\"running\"})",
     "legendFormat": "memory"
    }
   ]
  },
  {
   "title": "Block I/O",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (engine_host) (rate(docker_container_blkio_io_service_bytes_recursive_read{job=\"telegraf_docker_metrics\", platform=~\"$platform\", engine_host=~\"$node\", com_docker_swarm_service_name!=\"\", container_status=\"running\"}[5m]) + rate(docker_container_blkio_io_service_bytes_recursive_write{job=\"telegraf_docker_metrics\", platform=~\"$platform\", engine_host=~\"$node\", com_docker_swarm_service_name!=\"\", container_status=\"running\"}[5m])))",
     "legendFormat": "disk"
    }
   ]
  },
  {
   "title": "Network",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (engine_host) (rate(docker_container_net_rx_bytes{job=\"telegraf_docker_metrics\", platform=~\"$platform\", engine_host=~\"$node\", com_docker_swarm_service_name!=\"\", container_status=\"running\"}[5m]) + rate(docker_container_net_tx_bytes{job=\"telegraf_docker_metrics\", platform=~\"$platform\", engine_host=~\"$node\", com_docker_swarm_service_name!=\"\", container_status=\"running\"}[5m])))",
     "legendFormat": "network"
    }
   ]
  },
  { "title": "Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU over time",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (engine_host) (docker_container_cpu_usage_percent{job=\"telegraf_docker_metrics\", platform=~\"$platform\", engine_host=~\"$node\", com_docker_swarm_service_name!=\"\", container_status=\"running\"})",
     "legendFormat": "{{engine_host}}"
    }
   ]
  },
  {
   "title": "Memory over time",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (engine_host) (docker_container_mem_usage_percent{job=\"telegraf_docker_metrics\", platform=~\"$platform\", engine_host=~\"$node\", com_docker_swarm_service_name!=\"\", container_status=\"running\"})",
     "legendFormat": "{{engine_host}}"
    }
   ]
  },
  {
   "title": "Network usage over time",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (engine_host) (rate(docker_container_net_rx_bytes{job=\"telegraf_docker_metrics\", platform=~\"$platform\", engine_host=~\"$node\", com_docker_swarm_service_name!=\"\", container_status=\"running\"}[5m]) + rate(docker_container_net_tx_bytes{job=\"telegraf_docker_metrics\", platform=~\"$platform\", engine_host=~\"$node\", com_docker_swarm_service_name!=\"\", container_status=\"running\"}[5m]))",
     "legendFormat": "{{engine_host}}"
    }
   ]
  },
  {
   "title": "Stopped containers",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (engine_host) (docker_n_containers_stopped{job=\"telegraf_docker_metrics\", platform=~\"$platform\", engine_host=~\"$node\"})",
     "legendFormat": "{{engine_host}}"
    }
   ]
  },
  {
   "title": "Running containers",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (engine_host) (docker_n_containers_running{job=\"telegraf_docker_metrics\", platform=~\"$platform\", engine_host=~\"$node\"})",
     "legendFormat": "{{engine_host}}"
    }
   ]
  },
  {
   "title": "Block I/O over time",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (engine_host) (rate(docker_container_blkio_io_service_bytes_recursive_read{job=\"telegraf_docker_metrics\", platform=~\"$platform\", engine_host=~\"$node\", com_docker_swarm_service_name!=\"\", container_status=\"running\"}[5m]) + rate(docker_container_blkio_io_service_bytes_recursive_write{job=\"telegraf_docker_metrics\", platform=~\"$platform\", engine_host=~\"$node\", com_docker_swarm_service_name!=\"\", container_status=\"running\"}[5m]))",
     "legendFormat": "{{engine_host}}"
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Top services by CPU",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(15, avg by (com_docker_swarm_service_name) (docker_container_cpu_usage_percent{job=\"telegraf_docker_metrics\", platform=~\"$platform\", engine_host=~\"$node\", com_docker_swarm_service_name!=\"\", container_status=\"running\"}))",
     "legendFormat": "{{com_docker_swarm_service_name}}"
    }
   ]
  }
 ]
}