{
 "title": "TrueNAS – CPU",
 "tags": [
  "homelab",
  "truenas"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "label": "TrueNAS host", "query": "truenas.*" }
  ]
 },
 "panels": [
  {
   "title": "Avg CPU Temp",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(averageSeries(truenas.$host.cputemp.temperatures.*),'')"
    }
   ]
  },
  {
   "title": "Avg CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(averageSeries(asPercent(groupByNode(truenas.$host.cpu.*.{user,system,iowait,irq,softirq,nice,steal,guest,guest_nice},1,\"sum\"), groupByNode(truenas.$host.cpu.*.*,1,\"sum\"))), '')"
    }
   ]
  },
  {
   "title": "Avg CPU Idle",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(averageSeries(asPercent(groupByNode(truenas.$host.cpu.*.idle,1,\"sum\"), groupByNode(truenas.$host.cpu.*.*,1,\"sum\"))), '')"
    }
   ]
  },
  {
   "title": "Avg CPU IOWait",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "alias(averageSeries(asPercent(groupByNode(truenas.$host.cpu.*.iowait,1,\"sum\"), groupByNode(truenas.$host.cpu.*.*,1,\"sum\"))), '')"
    }
   ]
  },
  {
   "title": "CPU Usage by Host",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(asPercent(groupByNode(truenas.$host.cpu.*.{user,system,iowait,irq,softirq,nice,steal,guest,guest_nice},1,\"sum\"), groupByNode(truenas.$host.cpu.*.*,1,\"sum\")),1)"
    }
   ]
  },
  {
   "title": "CPU Usage by Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(asPercent(sumSeriesWithWildcards(truenas.$host.cpu.cpu*.{user,system,iowait,irq,softirq,nice,steal,guest,guest_nice},4), sumSeriesWithWildcards(truenas.$host.cpu.cpu*.{user,system,iowait,irq,softirq,nice,steal,guest,guest_nice,idle},4)),1,3)"
    }
   ]
  },
  {
   "title": "CPU Idle Residency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(asPercent(truenas.$host.cpu.cpu*.idle, sumSeriesWithWildcards(truenas.$host.cpu.cpu*.{user,system,iowait,irq,softirq,nice,steal,guest,guest_nice,idle},4)),1,3)"
    }
   ]
  },
  {
   "title": "CPU Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "aliasByNode(truenas.$host.cputemp.temperatures.*,1,4)"
    }
   ]
  },
  {
   "title": "CPU Guest by Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(truenas.$host.cpu.*.guest,1,3,4)"
    }
   ]
  },
  {
   "title": "CPU Guest Nice by Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(truenas.$host.cpu.*.guest_nice,1,3,4)"
    }
   ]
  },
  {
   "title": "CPU Idle by Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(truenas.$host.cpu.*.idle,1,3,4)"
    }
   ]
  },
  {
   "title": "CPU IOWait by Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(truenas.$host.cpu.*.iowait,1,3,4)"
    }
   ]
  },
  {
   "title": "CPU IRQ by Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(truenas.$host.cpu.*.irq,1,3,4)"
    }
   ]
  },
  {
   "title": "CPU Nice by Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(truenas.$host.cpu.*.nice,1,3,4)"
    }
   ]
  },
  {
   "title": "CPU SoftIRQ by Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(truenas.$host.cpu.*.softirq,1,3,4)"
    }
   ]
  },
  {
   "title": "CPU Steal by Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(truenas.$host.cpu.*.steal,1,3,4)"
    }
   ]
  },
  {
   "title": "CPU System by Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(truenas.$host.cpu.*.system,1,3,4)"
    }
   ]
  },
  {
   "title": "CPU User by Core",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "aliasByNode(truenas.$host.cpu.*.user,1,3,4)"
    }
   ]
  }
 ]
}