apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-terminal-exec
  annotations:
    argocd.argoproj.io/sync-wave: "6"
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-terminal-exec
  annotations:
    argocd.argoproj.io/sync-wave: "6"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-terminal-exec
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd
