apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - argocd-cm-terminal.yaml
  - argocd-repo-server-healer.yaml
  - argocd-terminal-exec-rbac.yaml
  - externalsecret.yaml
  - ingress.yaml
  - notifications-cm.yaml
  - secretstore.yaml
  - swarm-mcp-kubernetes-viewer-rbac.yaml
