apiVersion: v1
kind: Service
metadata:
  name: mcp-kubernetes
  namespace: mcp-kubernetes
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  selector:
    app.kubernetes.io/name: mcp-kubernetes
  ports:
    - name: http
      port: 8106
      targetPort: http
