apiVersion: config.kio.kasten.io/v1alpha1
kind: Profile
metadata:
  name: kasten-s3-profile
  namespace: kasten-io
spec:
  type: Location
  locationSpec:
    credential:
      secretType: AwsAccessKey
      secret:
        apiVersion: v1
        kind: Secret
        name: kasten-s3-secret
        namespace: kasten-io
    type: ObjectStore
    objectStore:
      name: kasten-backups
      objectStoreType: S3
      endpoint: http://192.168.1.26:9000
      region: us-east-1
      skipSSLVerify: true
