apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: privatebin-nightly
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  schedule: "0 8 * * *"
  template:
    includedNamespaces:
      - privatebin
    storageLocation: privatebin
    ttl: 336h0m0s
