apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: radarr-nightly
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  schedule: "0 3 * * *"
  template:
    includedNamespaces:
      - radarr
    storageLocation: radarr
    ttl: 336h0m0s
