# Velero MinIO credentials (committed per operator request; Vault/ESO disabled for now).
apiVersion: v1
kind: Secret
metadata:
  name: velero-s3-credentials
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-wave: "10"
type: Opaque
stringData:
  cloud: |
    [default]
    aws_access_key_id=nodadyoushutup
    aws_secret_access_key=S#nvhs89vher
