apiVersion: v1
data:
  VAULT_TOKEN: aHZzLjBqR1AxWFlVeFRQdmJQaWpmY3hsV1A3Ug==
kind: Secret
metadata:
  name: velero-vault-reader
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-wave: "5"
