apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: democratic-csi-nfs-node
  namespace: democratic-csi-nfs
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  template:
    spec:
      containers:
        - name: driver-registrar
          livenessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 5
