apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: langchain-agent-chat-registry
  namespace: langchain-agent-chat
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: langchain-agent-chat-vault
  target:
    name: langchain-agent-chat-registry
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {"auths":{"ghcr.io":{"username":"{{ .username }}","password":"{{ .password }}","auth":"{{ printf "%s:%s" .username .password | b64enc }}"}}}
  data:
    - secretKey: username
      remoteRef:
        key: k8s/langchain_agent_chat
        property: ghcr_username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: k8s/langchain_agent_chat
        property: ghcr_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
