apiVersion: v1
kind: Service
metadata:
  name: langchain-agent-chat
  namespace: langchain-agent-chat
  annotations:
    argocd.argoproj.io/sync-wave: "35"
spec:
  selector:
    app.kubernetes.io/name: langchain-agent-chat
  ports:
    - name: http
      port: 3000
      targetPort: http
