apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcp-terraform-app-env
  namespace: mcp-terraform
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: mcp-terraform-vault
  target:
    name: mcp-terraform-app-env
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      type: Opaque
      data:
        MCP_TERRAFORM_TOOLSETS: '{{ .toolsets | default "registry" }}'
        ENABLE_TF_OPERATIONS: '{{ .enable_tf_operations | default "false" }}'
        MCP_CORS_MODE: '{{ .mcp_cors_mode | default "strict" }}'
        TFE_ADDRESS: '{{ .tfe_address | default "" }}'
        TFE_TOKEN: '{{ .tfe_token | default "" }}'
        MCP_ALLOWED_ORIGINS: '{{ .mcp_allowed_origins | default "" }}'
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: k8s/mcp_terraform
        metadataPolicy: None
